name: deploy on remote server 
 
on: [push, pull_request] 
jobs: 
    build: 
        name: deploy 
        runs-on: ubuntu-latest 
        steps: 
            - name: deploy 
              uses: appleboy/ssh-action@v1.0.0 
              with: 
                host: sunbeam55.com 
                username: deploy 
                password: sunbeam 
                script: |
                    cd /home/deploy/Sunbeam_repo 
                    git checkout develop 
                    git pull origin develop 
                    docker compose down 
                    docker image rm $(docker image ls -a -q) 
                    docker compose up -d
